"""create_initial_tables

Revision ID: f474e551f78a
Revises: 
Create Date: 2026-04-01 16:48:05.020310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f474e551f78a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('training_days_per_week', sa.Integer(), nullable=True),
    sa.Column('garmin_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('perceived_sleep_hours', sa.Float(), nullable=True),
    sa.Column('general_feeling', sa.Integer(), nullable=True),
    sa.Column('workout_generated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_checkin_user_date')
    )
    op.create_index(op.f('ix_checkins_date'), 'checkins', ['date'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('garmin_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garmin_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type_key', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('training_effect_aerobic', sa.Float(), nullable=True),
    sa.Column('training_effect_anaerobic', sa.Float(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garmin_activities_garmin_activity_id'), 'garmin_activities', ['garmin_activity_id'], unique=True)
    op.create_index(op.f('ix_garmin_activities_started_at'), 'garmin_activities', ['started_at'], unique=False)
    op.create_index(op.f('ix_garmin_activities_type_key'), 'garmin_activities', ['type_key'], unique=False)
    op.create_index(op.f('ix_garmin_activities_user_id'), 'garmin_activities', ['user_id'], unique=False)
    op.create_table('garmin_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('active_kcal', sa.Float(), nullable=True),
    sa.Column('total_kcal', sa.Float(), nullable=True),
    sa.Column('avg_stress_level', sa.Integer(), nullable=True),
    sa.Column('body_battery_high', sa.Integer(), nullable=True),
    sa.Column('body_battery_low', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_stats_user_date')
    )
    op.create_index(op.f('ix_garmin_daily_stats_user_id'), 'garmin_daily_stats', ['user_id'], unique=False)
    op.create_table('garmin_hrv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv_last_night_avg', sa.Integer(), nullable=True),
    sa.Column('hrv_weekly_avg', sa.Integer(), nullable=True),
    sa.Column('hrv_status', sa.String(length=20), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('readiness_level', sa.String(length=20), nullable=True),
    sa.Column('readiness_feedback', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_hrv_user_date')
    )
    op.create_index(op.f('ix_garmin_hrv_user_id'), 'garmin_hrv', ['user_id'], unique=False)
    op.create_table('garmin_sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('light_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('awake_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_respiration', sa.Float(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_sleep_user_date')
    )
    op.create_index(op.f('ix_garmin_sleep_user_id'), 'garmin_sleep', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_garmin_sleep_user_id'), table_name='garmin_sleep')
    op.drop_table('garmin_sleep')
    op.drop_index(op.f('ix_garmin_hrv_user_id'), table_name='garmin_hrv')
    op.drop_table('garmin_hrv')
    op.drop_index(op.f('ix_garmin_daily_stats_user_id'), table_name='garmin_daily_stats')
    op.drop_table('garmin_daily_stats')
    op.drop_index(op.f('ix_garmin_activities_user_id'), table_name='garmin_activities')
    op.drop_index(op.f('ix_garmin_activities_type_key'), table_name='garmin_activities')
    op.drop_index(op.f('ix_garmin_activities_started_at'), table_name='garmin_activities')
    op.drop_index(op.f('ix_garmin_activities_garmin_activity_id'), table_name='garmin_activities')
    op.drop_table('garmin_activities')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_date'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
